# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Wireless In-Bore Ballistocardiography with 2.4GHz Beat Pilot Tone (BPT)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/mathieuboudreau/neurolibre-bpt_bcg  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

only_build_toc_files: true

# Binder link settings
use_binder_button                : true  # If 'true', add a binder button for interactive links
binderhub_url                    : "http://test.conp.cloud"  # The URL for your BinderHub. If no URL, use ""

execute:
  timeout: 600