#!/bin/bash
git clone https://github.com/mikgroup/sigpy.git
cd sigpy; pip install -e .; cd ..

git clone https://github.com/mikgroup/bpt_mrpub.git content/bpt_mrpub

repo2data -r binder/data_requirement.json
cp -r data/bpt_bcg-neurolibre/data content/data
